### ISSUE TITLE
Cannot run qc_report on Dorado generated bam

### ISSUE THREAD

**Issue by KunFang93** [streetslab/dimelo#111]
Hi,

Thanks for providing this wonderful package! I am a fresher for long read sequencing and Dimelo. Since the ONT recommend use Dorado to do basecallering, I generated my bam file with commands
```
dorado basecaller hac,6mA --no-trim --kit-name SQK-NBD114-24 --min-qscore 10 -r --output-dir ./fastq_modi pod5/
dorado demux --output-dir ./ --no-classify calls_2024-12-05_T01-25-36.bam --barcode-both-ends
dorado aligner mm39.mmi fastq_modi/ --output-dir align_modi  --mm2-opts "-k 15 -w 10" --threads 20
```
And my bam file looks like
```
74546560-ca9c-4051-a1d7-420e3b27d693    16      chr1    3100335 60      50S118M6D20M1I3M1D3M2D182M1D174M2D119M1D125M2D93M76S    *       0       0       ATGTATTGCTAAGGTTAAACCCTCCAGGAAAGTACCTCTGATCAGCACCTTCTGGTTGCAGATGGACAAGGAGTTGGCGAAATGAATGACAGACAGTTGGTTTAGTGAATGTCCCTATTGAAAGTAAATGCATTTTGTTTGATTACTGTCAACAATAAGAGTCACATACTCTAAACCTGTGGGGTTCTAGAGACTTAATAACATTACTTCCCTGAAGTTTGTATTCTCATTTTATATTTACATATTTGTTTTTAATTCTAATTTTTATTCATTCATTTATTTTATTTATTTACATTTCAAATGTTATTCCCTTTCCAGGTTTCCCCTCTGCAAGCCTGCTATCCCATCCCCTGCTACCCTGCTTCTTTGAGGGTGCTCCCACCCACCTAACCACTTCTGCCTTACCACCAAAACATTCCTCTAAACTGTGACATCAATCAAGGAACAAGGGCCTCCCCTCCCACTGATGCCAGATAAGGCCCCTTCAGTTCCTTCAGTCTCCTTTGGGGTTCCTGAGCTCATTCCTATATTTGCCTGCCAGCCTCTGCATCTATTGGTCAGGATCTAGCAGAACCTCTCAGAAGACAGCTGTATCAGGCTCCTGTCAGCAAGCACTTAAGATCAGCAAGAATCTGGTTTTGGTGTCTACATGTTTGATGGATCCCCAGATGGGAAGTATCTGGATGGCTGTTTCTTCAGTTTCTGCTCCATTCTTTGTCCTTATATTTCCTTTAGACAGGAGCAATTCTGGGTTAAAATTTTGGAGATGGGTGGGTGGACCCATTCCTCAAATATGGTGAGACATGCCTAACCTCTGGATATGGTCTCAACAGGTTCTCCTTCTTCTTTGTGGGATATTTCAGCTAATGTCATCCCCGTGGACACCTGAGGTGCTGATCAGAGGTACTTTCCTGGAGGGTTTAACCTTAGCAATACGTAATCCTAACGAAGTAAATAAGGACAG   ()ADIHIGFFCCCDFGC@>@=>A?@ABCF>>=>>>BCAEGECAA=::<?DEDEDA@@@CFFBA?@AAA@?BCCDDEB=;43223>CCFKJLIGFFDBCDEMEDEEFHDDCACABDGIKSMRFFIIPHIHHFIM<DDHG;@>DDCEDB6114852--9334355/..%$%%&-?A@ABDB>>=;43'&&,-//.+9=>?GIIMI@AACPDEC<77787><<=>>?B?CMSMJGEDIJLDEFEJIPGFEHIK@B>@AAABA===F@@82//2.--.?@46AA@:BHIGJKMGMSJLLIJILCEDCHE@A=<@FEDD@@9777GBBF>?@@CEDBA@AEDCCBCA>>?EFECBDCCA>>>@CCDDJOEEA@EEDD?<<@<>5:/00-/)+9;;;?LJMJDAABB@?@@CE@@A@EFEGGDDFCCLGFFGEEDEGCEIFKGD;C@CJLHEJHGEDBCFEEDCFBFGEEEDEDFBB8766:<ABDCA:9751060=>A=71003.-*(()=9435/03300*****66344FGKGGEEHIDCACBD>>?::*''&&+78;>>77;9320,++,=B@??>><<99//7>>DDEDDCDEGDCCB@@?@DFDCDEE;;;;EDFCAEHLIGHKGEEAACADCCESMGDCBCDDFCEDEJMHIHHIEAA@?AB@C><;;;B65=CGEGJIDGHCDAACDILIEE=BCECDB=8541112.//ACEEEDBAAEIMIOFCEIGDEEGGB@A@B65555445.,+85FKDHKJGCII>?>=ADAHHE8777QJHFDH<A@<<>>>@?.579?FFHDB@?@CBBBBEIJBDBC=:980,-,,@CBCACDBAABCFCEJGHJJEE7>ACFLCHFBAB@(';=9999JGI@EBG379QKKJKKJSMHKIBJKJIJIGI>GEFKOJLIGB==D?>@DBBFF8?556506'&&'+)('&%&$'&')(&%%%$##$######"   BC:Z:SQK-NBD114-24_barcode17    qs:f:19.1646    du:f:3.345      ns:i:16725      ts:i:10 mx:i:3  ch:i:45 st:Z:2024-11-15T01:03:13.360+00:00      rn:i:57    fn:Z:FBA80583_ea04ff91_33c7fa32_4.pod5  sm:f:378.828    sd:f:105.081    sv:Z:pa dx:i:0  RG:Z:33c7fa326d5bdc52258909cb36731f9a8dd8f77c_dna_r10.4.1_e8.2_400bps_hac@v5.0.0_SQK-NBD114-24_barcode17           MN:i:964        MM:Z:A+a.,0,0,0,0,0,0,0,0,0,0,0,3,0,1,1,2,1,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,2,0,6,0,11,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,2,3,1,0,0,5,0,2,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17,0,0,0,4,4,0,0,0,2,0,9,0,0,0,0,0,1,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0,6,1,1,3,0,0,0,0,0,0,0,0,0,1,0,0,0,0;      ML:B:C,65,165,132,187,55,22,98,87,157,104,28,43,28,175,22,27,130,21,17,28,21,19,50,82,32,20,22,18,30,204,58,63,161,14,206,21,165,14,16,54,129,19,100,39,240,184,83,46,244,29,168,64,42,16,18,26,44,14,20,180,42,78,18,12,23,18,69,33,13,24,20,18,12,24,44,74,65,56,38,204,182,24,15,117,46,16,104,98,82,119,28,132,80,29,194,68,80,200,97,35,71,33,34,50,60,54,97,65,58,19,26,13,31,13,106,32,15,106,22,26,12,88,47,168,30,13,33,47,33,15,54,37,139,24,71,161,115,42,18,33,175,184,194,145,125,149,57,88,15,56,18,49,17,14,51,19,87,27,35,23,29,24,45,21,23,59,59,110,27,73,15,19,67,13,64,57,140,22,51,159,254,31,29,22,89,144,46,166,28,15,195,14,57,58,37,69,16,133,25,250,242,14,58,209,151,63       NM:i:24 ms:i:1571       AS:i:1562       nn:i:0  de:f:0.0189349  tp:A:P  cm:i:103           s1:i:681        s2:i:65 MD:Z:118^CAGTTG2G20^A1A1^AC45T136^C6T163A3^TT119^G30C94^GG34G46T11      rl:i:174
```
When I run
``` 
dm.qc_report(f"{bamdir}/{prefix}_barcode17.bam", "Br", outdir)
```
I got error
```
>>> dm.qc_report(f"{bamdir}/{prefix}_barcode17.bam", "Br", outdir)
Processing reads: 11 batches [00:06,  1.69 batches/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kfang/miniforge3/envs/dimelo_new/lib/python3.7/site-packages/dimelo/qc.py", line 323, in qc_report
    filebamIn, sampleName, outDir, cores
  File "/home/kfang/miniforge3/envs/dimelo_new/lib/python3.7/site-packages/dimelo/qc.py", line 146, in parse_bam_read
    unit=" batches",
  File "/home/kfang/miniforge3/envs/dimelo_new/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/kfang/miniforge3/envs/dimelo_new/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/kfang/miniforge3/envs/dimelo_new/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/kfang/miniforge3/envs/dimelo_new/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/kfang/miniforge3/envs/dimelo_new/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/kfang/miniforge3/envs/dimelo_new/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/kfang/miniforge3/envs/dimelo_new/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/kfang/miniforge3/envs/dimelo_new/lib/python3.7/site-packages/dimelo/utils.py", line 61, in execute_sql_command
    c.executemany(command, values)
sqlite3.IntegrityError: UNIQUE constraint failed: reads_Br.name
```

But I could successfully run qc_report on test.bam
```
>>> dm.qc_report("/home/kfang/data/kfang/Software/dimelo/dimelo/test/data/mod_mappings_subset.bam", "test", outdir)
Processing reads:100%█████████████████████| 10/10 [00:00<00:00, 10.48 batches/s]
mean length:  11679
num reads:  9012
num bases:  105251148
```
I did notice mod_mappings_subset.bam contains less column compared to what I got.

I wondered if you could shed some light on how to deal with this incompatibility? Thanks in advance!

Best,
Kun

**Comment by KunFang93** [comment]
Remove the secondary and supplementary reads solve this...
